version: '3.8'

services:
  node-engine:
    build:
      context: ..
      dockerfile: infra/node-engine.Dockerfile
    ports:
      - "5001:5001"

  gateway:
    build:
      context: ..
      dockerfile: infra/gateway.Dockerfile
    ports:
      - "3000:3000"
